[DRAFT] Add logging test that supports ES and AWS CloudWatch
cloud-bulldozer/e2e-benchmarking pull request #147
Opened 2021-03-24 10:42 UTC by dry923

# Description
Adds support for running logging tests. This works for both Elasticsearch backed and AWS CloudWatch backed configurations.

2021-05-07 19:33 UTC, whitleykeith requested changes

2021-05-07 19:33 UTC, whitleykeith commented on workloads/logging/common.sh
> +  status=$(oc get benchmark -n my-ripsaw log-generator-${UUID} -o jsonpath="{.status.state}")
see line 148

2021-05-07 20:14 UTC, whitleykeith approved these changes
lgtm!

2021-05-10 13:26 UTC, dry923 commented
The ES portion has been tested. The CloudWatch backend has not yet. We can treat the aws portion as a WIP and merge this sooner if needed for the ES part.

2021-05-10 14:18 UTC, whitleykeith commented
i'm gonna merge since the ES option is stable

2021-05-10 14:19 UTC, merged