Cluster-density refactor
cloud-bulldozer/e2e-benchmarking pull request #351
Opened 2022-03-24 17:07 UTC by rsevilla87

The current cluster-density workload is outdated, and not very
representative of a real case scenario. It makes an extensive usage of
builds, the extensive usage of this object generates lot of delays in
the workload because of long building times and can also lead to timeouts.
Also, generating such amount of build objects is not very representative
of a real case scenario.

Replacing most of these builds by deployments and more services will generate a
similar CPU usage in the control plane and will help to generate a more
deterministic load.

Results seen on a 120 worker nodes cluster using executing 1000 iterations:
![image](https://user-images.githubusercontent.com/4614641/159971506-36a89b1e-4956-42a1-93ee-55ff0c8f4f5f.png)

![image](https://user-images.githubusercontent.com/4614641/159971702-efc465f3-2c7c-43cf-bef2-acc1a8595813.png)

![image](https://user-images.githubusercontent.com/4614641/159971332-9bb56e73-2ede-43eb-a881-223fba36012b.png)

![image](https://user-images.githubusercontent.com/4614641/159971390-133b2445-91f1-447a-9e63-700cdb7e29bb.png)

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### Description

### Fixes

2022-03-24 19:24 UTC, smalleni commented
@rsevilla87 I generally like the idea but would believe we should start having > 1 endpoint per service. Thoughts?

2022-03-24 19:31 UTC, smalleni commented
I like it, finally > 1 endpoint/service/ Thoughts about multiple ports/service as that would increase the number of endpoints/service further?

2022-03-24 22:56 UTC, rsevilla87 commented
> I like it, finally > 1 endpoint/service/ Thoughts about multiple ports/service as that would increase the number of endpoints/service further?

Keep in mind that each service is backing 2 pods, and five services are created in each iteration. In a 1k scenario would mean 5000 services backing 10000 pods, as shown in the capture above, the programming latency got increased ~x2 in this scenario, in a 4k scenario that increase would be at least x8

2022-03-25 15:33 UTC, smalleni commented
> > I like it, finally > 1 endpoint/service/ Thoughts about multiple ports/service as that would increase the number of endpoints/service further?
> 
> Keep in mind that each service is backing 2 pods, and five services are created in each iteration. In a 1k scenario would mean 5000 services backing 10000 pods, as shown in the capture above, the programming latency got increased ~x2 in this scenario, in a 4k scenario that increase would be at least x8 in OpenShiftSDN

Right, I'm just talking about changing the service template to back multiple ports instead of just one port per service.

2022-03-30 09:16 UTC, rsevilla87 commented
> > > I like it, finally > 1 endpoint/service/ Thoughts about multiple ports/service as that would increase the number of endpoints/service further?
> > 
> > 
> > Keep in mind that each service is backing 2 pods, and five services are created in each iteration. In a 1k scenario would mean 5000 services backing 10000 pods, as shown in the capture above, the programming latency got increased ~x2 in this scenario, in a 4k scenario that increase would be at least x8 in OpenShiftSDN
> 
> Right, I'm just talking about changing the service template to back multiple ports instead of just one port per service.

Hey Sai, I get your idea, however I don't understand what you want to achieve by adding more complexity to the workload. We have to be able to execute 4K iterations of this workload in a 252 worker node scenario.

FYI, these are some of the metrics I got from a 4k test on a 252 node cluster:

![image](https://user-images.githubusercontent.com/4614641/160795844-d5923025-d3dd-4c5b-bbc9-f12b76b6d5f7.png)
![image](https://user-images.githubusercontent.com/4614641/160796892-1c89ae4b-87a9-4415-a1b1-ec3e814726d8.png)
![image](https://user-images.githubusercontent.com/4614641/160795981-a9cc32c1-86da-4d4e-a081-088261b45cde.png)
![image](https://user-images.githubusercontent.com/4614641/160796096-eb3b756d-c25f-4351-85c8-48e560ce6d18.png)

2022-03-31 11:34 UTC, rsevilla87 commented
@smalleni, I've been thinking of your suggestion and after some testing, I've added an extra port to each service/port, I think it's worth for our regular testing

2022-03-31 17:48 UTC, smalleni commented
> @smalleni, I've been thinking of your suggestion and after some testing, I've added an extra port to each service/port, I think it's worth for our regular testing

Thanks @rsevilla87. I mostly asked for this based on customer deployments and previous experience with you know who :)

2022-03-31 17:49 UTC, smalleni requested changes

2022-03-31 17:49 UTC, smalleni commented on workloads/kube-burner/README.md
> +- 5 services, each ont pointing to the TCP/8080 port of one of the previous deployments
Update with new port details as well.

2022-04-05 14:41 UTC, dry923 approved these changes
LGTM!

2022-04-05 15:04 UTC, merged