Remove port, username and password from ES variables
cloud-bulldozer/e2e-benchmarking pull request #61
Opened 2020-10-22 13:44 UTC by rsevilla87

Depends on: https://github.com/cloud-bulldozer/benchmark-operator/pull/438

Will also require some changes in https://github.com/openshift-scale/scale-ci-pipeline

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

2020-10-26 13:09 UTC, jtaleric commented on workloads/kube-burner/README.md
>  | **ES_SERVER**        | Elastic search endpoint         | https://search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com|
this should be `https/http/g`

2020-10-26 13:10 UTC, jtaleric commented on workloads/kube-burner/common.sh
>  export ES_SERVER=${ES_SERVER:-https://search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com}
`https/http/g`

2020-10-26 13:12 UTC, jtaleric requested changes
Since we are referencing the public ES server, lets be sure to call out `http` vs `https` as if we reference `https` we should call out the port as 443 vs 80.

2020-10-26 16:41 UTC, jtaleric approved these changes
LGTM!

2020-12-16 19:32 UTC, whitleykeith approved these changes

2021-01-07 13:47 UTC, mohit-sheth approved these changes
LGTM

2021-01-07 15:15 UTC, merged