POC: kube-burner-ocp integration
cloud-bulldozer/e2e-benchmarking pull request #670
Opened 2024-01-17 11:55 UTC by rsevilla87

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

Integrating `kube-burner-ocp` v1.0.0, built using the most recent code.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

2024-01-19 09:12 UTC, venkataanil approved these changes
LGTM

2024-01-19 09:12 UTC, venkataanil commented on workloads/kube-burner-ocp-wrapper/run.sh
> +KUBE_BURNER_VERSION=${KUBE_BURNER_VERSION:-1.0.0}
Let's rename it to KUBE_BURNER_OCP_VERSION to reflect kube-burner-ocp release

2024-01-19 15:33 UTC, mohit-sheth approved these changes
lgtm

2024-01-19 15:34 UTC, krishvoor approved these changes
/lgtm

2024-01-19 15:59 UTC, jtaleric requested changes
I would like to see us verify this doesn't break *anything* in prow.

2024-01-19 16:00 UTC, jtaleric commented
things I think it will break are the jobs which use legacy workloads that QE depends on.
 
 cc @paigerube14 @nathan-weinberg @svetsa-rh

2024-01-19 21:15 UTC, svetsa-rh commented
> I would like to see us verify this doesn't break anything in prow.
@paigerube14 Anything in Jenkins as well that will break because of this change?
@jtaleric AFAIK, our tests in Prow use ocp version anyway. Also, if we want to verify nothing in Prow is breaking because of this change, we set KUBE_BURNER_VERSION explicitly and try? Or something more?

2024-01-19 21:24 UTC, paigerube14 commented
@svetsa-rh no, ran a quick test and no changes are needed in jenkins since we're updating the run script that we call 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/899/console

2024-01-22 00:31 UTC, nathan-weinberg commented
if the PerfScale QE job is still working this should be fine for NetObserv QE as well - thanks for checking @jtaleric!

2024-01-23 21:32 UTC, rsevilla87 commented
> I would like to see us verify this doesn't break _anything_ in prow.

Let's try it using rehearsals

2024-01-24 15:36 UTC, jtaleric approved these changes
lgtm

2024-01-24 15:38 UTC, merged